data = read.table("household_power_consumption.txt", sep=";", header=TRUE)
Date <- as.Date(strptime(data$Date, format="%d/%m/%Y"))
data$Date <- Date
d <- subset(data,Date == "2007-02-01")
d1 <- subset(data,Date == "2007-02-02")
finaldata <- rbind(d,d1)
png("plot4.png", width=480, height=480, units='px')
par(mfrow = c(2,2))
plot(finaldata$Global_active_power, type='l', xaxt='n', ylab="Global Active Power")
axis(1,at = c(0,1500,2900),labels=c( 'Thu', 'Fri', 'Sat'))
finaldata$Voltage <- as.numeric(finaldata$Voltage)
plot(finaldata$Voltage, type='l', xaxt = 'n', ylab = 'Voltage')
axis(1,at = c(0,1500,2900),labels=c( 'Thu', 'Fri', 'Sat'))
plot(finaldata$Sub_metering_1, col='black', type='l', xaxt = 'n', ylab='Energy sub metering')
lines(finaldata$Sub_metering_2, col='red')
lines(finaldata$Sub_metering_3, col='blue')
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=1, col=c('black', 'red','blue'))
axis(1,at = c(0,1500,2900),labels=c( 'Thu', 'Fri', 'Sat'))
finaldata$Global_reactive_power <- as.numeric(finaldata$Global_reactive_power)
plot(finaldata$Global_reactive_power, type='l', xaxt='n', ylab='Global reactive power')
axis(1,at = c(0,1500,2900),labels=c( 'Thu', 'Fri', 'Sat'))
dev.off()
